config/routes.rb
Rw::Application.routes.draw do
  get "related_cmt/show"

  resources :comments

  get "tagged_post/tag_cloud"
  get "tagged_post/index"

  get "welcome/index"

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable_on :keywords
  has_many :comments, :dependent => :destroy

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml

  def index
    @articles = Article.all
    @tags = Article.tag_counts_on(:keywords)

    @cmt_counter = Hash.new
    @articles.each do |article|
      @cmt_counter[article.id] = related_cmts(article.id).size
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])
    session[:article_id] = @article.id
    @related_cmts = related_cmts(@article.id)
      
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_form.html.erb
<%= javascript_include_tag :ckeditor %>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_field :abstract %>
  </div>
  <div class="field">
    <%= ckeditor_textarea("article", "main_body", :width => '100%', :height => '200px') %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keyword_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div id = "title_counter" >
    <h2><%= article.title %></h2>
    <h1><%= @cmt_counter[article.id] %></h1>
  </div>

  <div id="main_body">
    <p><%= raw article.main_body %></p>

    <div class="control_link">
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
    </div>

    <p> keyword: 
    <% article.keyword_list.each do |keyword|  %>
      <%= link_to keyword, { :action => :index, 
        :controller => :tagged_post, 
        :tag_name=> keyword }
      %>
    <% end %>
    </p>
  </div>
<% end %>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @article.title %> </h2>
<p> <%= sanitize @article.main_body %> </p>

<p>
  <b>KeyWords:</b> <%= @article.keyword_list %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<%= link_to 'comment', new_comment_path %>
<br />

<%= render 'related_cmt/show' %>