config/routes.rb
Rw::Application.routes.draw do
  get "related_cmt/show"

  resources :comments

  get "tagged_post/tag_cloud"
  get "tagged_post/index"

  get "welcome/index"

  resources :articles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rw</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<script type="text/javascript" src="glossy.js"></script>
</head>

<div id = "banner" >
  <h1>Rover Way <span> Records of my Linux and Rails </span> </h1>
</div>

   
<div id = "container3" >
  <div id = "container2">
    <div id = "container1">

      <div id = "left" >
        <div id="navlist">
          <p><%= link_to "Home", welcome_index_url %></p>
          <p><%= link_to "Admin", articles_url %></p>
          <p><a href="#">About Me</a></p> 
          <br />
        </div>

        <h2> Tag Cloud </h2>
        <% if @tags %>
          <%= render 'tagged_post/tag_cloud' %>
        <% end %>
      </div>

      <div id = "main">
          <%= yield %>
      </div>

      <div id = "right">
        <h2> Categories </h2>
        <ul>
          <li> Linux </li>
          <li> Rails </li>
          <li> Mass things </li>
        </ul>
        <h2> Recent Comments </h2>
        <ul>
          <li> comment 1 </li>
          <li> comment 2 </li>
          <li> comment 3 </li>
        </ul>
      </div>

    </div>
  </div>
</div>

<div id = "bottom_line" >
</div>

<div id = "footer">
  <h1> footer </h1>
</div>
</html>